name: Add issues to project

on:
  issues:
    types:
      - opened
      - transferred

jobs:
  add-to-project:
    name: Add issues to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/TheOdinProject/projects/12
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
